DROP TABLE IF EXISTS toxicity CASCADE;
DROP TABLE IF EXISTS user_search_history CASCADE;
DROP TABLE IF EXISTS plants CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password_digest VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS plants (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  sci_name VARCHAR(255) NOT NULL,
  common_names TEXT,
  family VARCHAR(255) NOT NULL,
  aspca_url VARCHAR(255) NOT NULL,
  image_url VARCHAR(255) NOT NULL
);

CREATE TABLE user_search_history (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  plant_id INTEGER REFERENCES plants(id) ON DELETE CASCADE,
  sci_name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  info_url VARCHAR(255) NOT NULL,
  user_img_url VARCHAR(255) NOT NULL,
  common_names TEXT NOT NULL,
  date TIMESTAMP NOT NULL
);

CREATE TABLE toxicity (
  id SERIAL PRIMARY KEY NOT NULL,
  plant_id INTEGER REFERENCES plants(id) ON DELETE CASCADE,
  animal VARCHAR(255) NOT NULL,
  toxic BOOLEAN NOT NULL
);